language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.2
install:
  - pip install Django==$DJANGO_VERSION
script:
  - python setup.py test
branches:
  only:
    - master
