language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.2
install:
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run setup.py test
after_success:
  - coveralls
branches:
  only:
    - master
